apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    service: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      name: jenkins
      nodePort: 32002
      targetPort: 8080
    - port: 50000
      name: jnlp
      nodePort: 32005
      targetPort: 50000
  selector:
    service: jenkins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  labels:
    service: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    service: jenkins
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: jenkins
  template:
    metadata:
      labels:
        service: jenkins
    spec:
      containers:
      - image: 184.72.140.182:32003/jenkins/jenkins-image:latest
        name: jenkins
        command: ["/bin/bash"]
        args: ["-c", "pass=`cat /var/jenkins_home/secrets/initialAdminPassword` && echo 'jenkins.model.Jenkins.instance.securityRealm.createAccount(\"alexey\", \"Ins1ght\")' | java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -auth admin:$pass -s http://184.72.140.182:32002/ groovy ="]
        ports:
        - containerPort: 8080
          name: jenkins-port
          protocol: TCP
        volumeMounts:
          - name: jenkins-ps
            mountPath: "/var"
      volumes:
        - name: jenkins-ps
          persistentVolumeClaim:
            claimName: jenkins-pv-claim