apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    service: jenkins
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 38080
    targetPort: 8080
  selector:
    service: jenkins
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: jenkins
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: jenkins
  template:
    metadata:
      labels:
        service: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.73.1
        ports:
        - containerPort: 8080