apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-10-25T17:11:10Z
  name: aikubernetes.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://aikubernetes-k8s-local-state-store/aikubernetes.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
      volumeSize: 2
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
      volumeSize: 2
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.7.4
  masterInternalName: api.internal.aikubernetes.k8s.local
  masterPublicName: api.aikubernetes.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-10-25T17:11:10Z
  labels:
    kops.k8s.io/cluster: aikubernetes.k8s.local
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 8
  subnets:
  - us-east-1a
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-10-25T17:11:10Z
  labels:
    kops.k8s.io/cluster: aikubernetes.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Node
  rootVolumeSize: 8
  subnets:
  - us-east-1a