apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  labels:
    service: kube-registry
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 32003
    targetPort: 5000
  selector:
    service: kube-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-registry-pv-claim
  labels:
    service: kube-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    service: kube-registry
  name: kube-registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kube-registry
  template:
    metadata:
      labels:
        service: kube-registry
    spec:
      containers:
      - image: registry:2
        name: registry
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
          name: kube-registry-port
          protocol: TCP
        volumeMounts:
          - name: kube-registry-persistent-storage
            mountPath: "/var/lib/registry"
      volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: kube-registry-pv-claim