apiVersion: v1
kind: Service
metadata:
  name: samsara
  labels:
    service: samsara
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    service: samsara
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    service: samsara
  name: samsara-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      service: samsara
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        service: samsara
    spec:
      initContainers:
        - name: init-mydb
          image: postgres:9.3
          env:
          - name: PGPORT
            value: "32001"
          - name: PGDATABASE
            value: auradb
          - name: PGUSER
            value: aura
          - name: PGPASSWORD
            value: mysecretpassword
          command: ['/bin/bash', '-c', 'apt update && apt install curl -y && export PGHOST=`curl http://169.254.169.254/latest/meta-data/public-ipv4` && while [ 1 ]; do psql && break || sleep 5; done']
      containers:
      - image: 54.174.180.88:32003/samsara:latest
        name: samsara
        env:
        - name: DB_HOST
          value: "postgresdb.default.svc.cluster.local"
        - name: DB_NAME
          value: auradb
        - name: DB_USER
          value: aura
        - name: DB_PASS
          value: mysecretpassword
        ports:
        - containerPort: 9000
          protocol: TCP
          name: samsara-port
        readinessProbe:
         httpGet:
           path: /login
           port: 9000
         initialDelaySeconds: 10
         periodSeconds: 5


